export type PaletteTokens = Record<
  | "background"
  | "foreground"
  | "card"
  | "card-foreground"
  | "popover"
  | "popover-foreground"
  | "primary"
  | "primary-foreground"
  | "secondary"
  | "secondary-foreground"
  | "muted"
  | "muted-foreground"
  | "accent"
  | "accent-foreground"
  | "destructive"
  | "destructive-foreground"
  | "border"
  | "input"
  | "ring"
  | "sidebar"
  | "sidebar-foreground",
  string
>;

export type Palette = {
  id: string;
  name: string;
  swatch: string[];
  tokens: PaletteTokens;
};

// ponytail: 10 fixed presets, stored as id only in siteConfig. Token maps are
// duplicated in storefront/lib/palettes.ts — keep in sync when editing.
export const PALETTES: Palette[] = [
  {
    id: "ash-moss",
    name: "Fullbleed",
    swatch: ["#000000", "#ffffff", "#737373", "#e5e5e5", "#f4f4f4"],
    tokens: {
      background: "#ffffff",
      foreground: "#000000",
      card: "#ffffff",
      "card-foreground": "#000000",
      popover: "#ffffff",
      "popover-foreground": "#000000",
      primary: "#000000",
      "primary-foreground": "#ffffff",
      secondary: "#f4f4f4",
      "secondary-foreground": "#000000",
      muted: "#f4f4f4",
      "muted-foreground": "#6b7280",
      accent: "#f4f4f4",
      "accent-foreground": "#000000",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#e5e5e5",
      input: "#d4d4d4",
      ring: "#000000",
      sidebar: "#ffffff",
      "sidebar-foreground": "#000000",
    },
  },
  {
    id: "ocean",
    name: "Ocean Breeze",
    swatch: ["#0e7490", "#22d3ee", "#38bdf8", "#f4f9fc", "#0b1e2c"],
    tokens: {
      background: "#f4f9fc",
      foreground: "#0b1e2c",
      card: "#ffffff",
      "card-foreground": "#0b1e2c",
      popover: "#ffffff",
      "popover-foreground": "#0b1e2c",
      primary: "#0e7490",
      "primary-foreground": "#ffffff",
      secondary: "#22d3ee",
      "secondary-foreground": "#083344",
      muted: "#e6f1f7",
      "muted-foreground": "#4b6372",
      accent: "#38bdf8",
      "accent-foreground": "#082f49",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#cfe2ee",
      input: "#cfe2ee",
      ring: "#0e7490",
      sidebar: "#eaf4fa",
      "sidebar-foreground": "#0b1e2c",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    swatch: ["#ea580c", "#f97316", "#ec4899", "#ffedd5", "#2a1609"],
    tokens: {
      background: "#fff7ed",
      foreground: "#2a1609",
      card: "#ffffff",
      "card-foreground": "#2a1609",
      popover: "#ffffff",
      "popover-foreground": "#2a1609",
      primary: "#ea580c",
      "primary-foreground": "#ffffff",
      secondary: "#f97316",
      "secondary-foreground": "#431407",
      muted: "#ffedd5",
      "muted-foreground": "#8a5a3b",
      accent: "#ec4899",
      "accent-foreground": "#ffffff",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#fed7aa",
      input: "#fed7aa",
      ring: "#ea580c",
      sidebar: "#ffedd5",
      "sidebar-foreground": "#2a1609",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    swatch: ["#0b1120", "#1e293b", "#60a5fa", "#a78bfa", "#e2e8f0"],
    tokens: {
      background: "#0b1120",
      foreground: "#e2e8f0",
      card: "#111827",
      "card-foreground": "#e2e8f0",
      popover: "#111827",
      "popover-foreground": "#e2e8f0",
      primary: "#60a5fa",
      "primary-foreground": "#0b1120",
      secondary: "#1e293b",
      "secondary-foreground": "#e2e8f0",
      muted: "#1e293b",
      "muted-foreground": "#94a3b8",
      accent: "#a78bfa",
      "accent-foreground": "#0b1120",
      destructive: "#f87171",
      "destructive-foreground": "#0b1120",
      border: "#1f2937",
      input: "#1f2937",
      ring: "#60a5fa",
      sidebar: "#0f172a",
      "sidebar-foreground": "#e2e8f0",
    },
  },
  {
    id: "forest",
    name: "Forest",
    swatch: ["#166534", "#22c55e", "#84cc16", "#e3efe5", "#14261b"],
    tokens: {
      background: "#f2f7f2",
      foreground: "#14261b",
      card: "#ffffff",
      "card-foreground": "#14261b",
      popover: "#ffffff",
      "popover-foreground": "#14261b",
      primary: "#166534",
      "primary-foreground": "#ffffff",
      secondary: "#22c55e",
      "secondary-foreground": "#052e16",
      muted: "#e3efe5",
      "muted-foreground": "#4a6351",
      accent: "#84cc16",
      "accent-foreground": "#1a2e05",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#cfe3d3",
      input: "#cfe3d3",
      ring: "#166534",
      sidebar: "#e6f0e7",
      "sidebar-foreground": "#14261b",
    },
  },
  {
    id: "lavender",
    name: "Lavender",
    swatch: ["#7c3aed", "#a78bfa", "#c084fc", "#ece7f5", "#231a38"],
    tokens: {
      background: "#f6f3fb",
      foreground: "#231a38",
      card: "#ffffff",
      "card-foreground": "#231a38",
      popover: "#ffffff",
      "popover-foreground": "#231a38",
      primary: "#7c3aed",
      "primary-foreground": "#ffffff",
      secondary: "#a78bfa",
      "secondary-foreground": "#2e1065",
      muted: "#ece7f5",
      "muted-foreground": "#6d6283",
      accent: "#c084fc",
      "accent-foreground": "#4a044e",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#ddd5ea",
      input: "#ddd5ea",
      ring: "#7c3aed",
      sidebar: "#ece7f5",
      "sidebar-foreground": "#231a38",
    },
  },
  {
    id: "coral",
    name: "Coral Reef",
    swatch: ["#e11d48", "#fb7185", "#0d9488", "#fbe5e0", "#24110c"],
    tokens: {
      background: "#fdf4f0",
      foreground: "#24110c",
      card: "#ffffff",
      "card-foreground": "#24110c",
      popover: "#ffffff",
      "popover-foreground": "#24110c",
      primary: "#e11d48",
      "primary-foreground": "#ffffff",
      secondary: "#fb7185",
      "secondary-foreground": "#4c0519",
      muted: "#fbe5e0",
      "muted-foreground": "#8a4f3f",
      accent: "#0d9488",
      "accent-foreground": "#ffffff",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#f5cfc2",
      input: "#f5cfc2",
      ring: "#e11d48",
      sidebar: "#fbe9e4",
      "sidebar-foreground": "#24110c",
    },
  },
  {
    id: "golden",
    name: "Golden Hour",
    swatch: ["#d97706", "#f59e0b", "#b45309", "#f6ecd3", "#2a1d0a"],
    tokens: {
      background: "#fdf9ef",
      foreground: "#2a1d0a",
      card: "#ffffff",
      "card-foreground": "#2a1d0a",
      popover: "#ffffff",
      "popover-foreground": "#2a1d0a",
      primary: "#d97706",
      "primary-foreground": "#ffffff",
      secondary: "#f59e0b",
      "secondary-foreground": "#451a03",
      muted: "#f6ecd3",
      "muted-foreground": "#7d6a44",
      accent: "#b45309",
      "accent-foreground": "#ffffff",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#ecdcb8",
      input: "#ecdcb8",
      ring: "#d97706",
      sidebar: "#f6edd8",
      "sidebar-foreground": "#2a1d0a",
    },
  },
  {
    id: "slate",
    name: "Slate Mono",
    swatch: ["#334155", "#64748b", "#475569", "#f1f5f9", "#0f172a"],
    tokens: {
      background: "#f8fafc",
      foreground: "#0f172a",
      card: "#ffffff",
      "card-foreground": "#0f172a",
      popover: "#ffffff",
      "popover-foreground": "#0f172a",
      primary: "#334155",
      "primary-foreground": "#ffffff",
      secondary: "#64748b",
      "secondary-foreground": "#f1f5f9",
      muted: "#f1f5f9",
      "muted-foreground": "#64748b",
      accent: "#475569",
      "accent-foreground": "#ffffff",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#334155",
      sidebar: "#f1f5f9",
      "sidebar-foreground": "#0f172a",
    },
  },
  {
    id: "berry",
    name: "Berry",
    swatch: ["#be185d", "#db2777", "#a21caf", "#f6e3ed", "#2c1120"],
    tokens: {
      background: "#fbf3f7",
      foreground: "#2c1120",
      card: "#ffffff",
      "card-foreground": "#2c1120",
      popover: "#ffffff",
      "popover-foreground": "#2c1120",
      primary: "#be185d",
      "primary-foreground": "#ffffff",
      secondary: "#db2777",
      "secondary-foreground": "#500724",
      muted: "#f6e3ed",
      "muted-foreground": "#8a5b70",
      accent: "#a21caf",
      "accent-foreground": "#ffffff",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#eccfdd",
      input: "#eccfdd",
      ring: "#be185d",
      sidebar: "#f6e7ef",
      "sidebar-foreground": "#2c1120",
    },
  },
  {
    id: "citrus",
    name: "Citrus",
    swatch: ["#65a30d", "#a3e635", "#eab308", "#f0f7dd", "#1c2408"],
    tokens: {
      background: "#fbfef4",
      foreground: "#1c2408",
      card: "#ffffff",
      "card-foreground": "#1c2408",
      popover: "#ffffff",
      "popover-foreground": "#1c2408",
      primary: "#65a30d",
      "primary-foreground": "#ffffff",
      secondary: "#a3e635",
      "secondary-foreground": "#365314",
      muted: "#f0f7dd",
      "muted-foreground": "#5f6b3e",
      accent: "#eab308",
      "accent-foreground": "#422006",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#dfecc2",
      input: "#dfecc2",
      ring: "#65a30d",
      sidebar: "#f1f8e0",
      "sidebar-foreground": "#1c2408",
    },
  },
];

export const getPalette = (id?: string | null): Palette | undefined =>
  PALETTES.find((p) => p.id === id);
